language: node_js
sudo: false
node_js:
  - '4.1'
addons:
  apt:
    packages:
    - s3cmd
    - ruby
install:
  - gem install sass
  - gem install scss_lint
  - npm install -g gulp
before_script:
  - npm install
script:
  - gulp build
  - sh deploy.sh